### ISSUE TITLE
Option[Double] is deserialized as String for XmlMapper

### ISSUE THREAD

**Issue by leryss** [FasterXML/jackson-module-scala#564] opened 2021-12-21 16:14 UTC
I'm using the following maven dependencies
```   
   <dependency>
      <groupId>com.fasterxml.jackson.module</groupId>
      <artifactId>jackson-module-scala_2.12</artifactId>
      <version>2.13.0</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-xml</artifactId>
      <version>2.13.0</version>
    </dependency>
```

I'm trying to deserialize XML with XmlMapper and with the DefaultScalaModule, but for fields like `val myFloat: Option[Double],` im getting the following error when doing `myFloat.get`:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Double (java.lang.String and java.lang.Double are in module java.base of loader 'bootstrap')
  at scala.runtime.BoxesRunTime.unboxToDouble(BoxesRunTime.java:114)
  at serialization.BaseSerializationTest.$anonfun$new$2(BaseSerializationTest.scala:66)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSpecLike$$anon$1.apply(FunSpecLike.scala:454)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
```

And this also happens for Option[Integer]

**Comment by pjfanning** [comment] 2021-12-21 17:54
Can you provide the actual reproducible test case? And please have a good read of https://github.com/FasterXML/jackson-module-scala/wiki/FAQ. It describes some ways to work around the issues with Options and Collections that wrap primitives.

Also, if you are using Scala 3, https://github.com/pjfanning/jackson-scala3-reflection-extensions might be useful.

**Comment by pjfanning** [comment] 2022-01-29 19:35
Closing this due to lack of user response

**Closed by pjfanning** 2022-01-29 19:35 UTC
