### ISSUE TITLE
Conflicting setter definitions for property 

### ISSUE THREAD

**Issue by kgignatyev** [FasterXML/jackson-module-scala#88] opened 2013-07-02 21:36 UTC
I have compiled latest snapshot for Scala 2.10 and facing this issue:

Conflicting setter definitions for property "mapZoom": kgi.mcytravel.wsite.data.SearchCriteria#setMapZoom(1 params) vs kgi.mcytravel.wsite.data.SearchCriteria#mapZoom_$eq(1 params)

scala generated equality method confuses com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder

com.fasterxml.jackson.databind.JsonMappingException: Conflicting setter definitions for property &quot;mapZoom&quot;: kgi.mcytravel.wsite.data.SearchCriteria#setMapZoom(1 params) vs kgi.mcytravel.wsite.data.SearchCriteria#mapZoom_$eq(1 params)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:272)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:247)
    at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:146)
    at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:322)
    at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:2990)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2884)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
    at kgi.mcytravel.wsite.data.converter.SearchCriteriaToJson.convert(SearchCriteriaToJson.scala:25)
    at kgi.mcytravel.wsite.data.converter.SearchCriteriaToJsonSpec$$anonfun$2.apply(SearchCriteriaToJsonSpec.scala:32)
    at kgi.mcytravel.wsite.data.converter.SearchCriteriaToJsonSpec$$anonfun$2.apply(SearchCriteriaToJsonSpec.scala:26)
Caused by: java.lang.IllegalArgumentException: Conflicting setter definitions for property &quot;mapZoom&quot;: kgi.mcytravel.wsite.data.SearchCriteria#setMapZoom(1 params) vs kgi.mcytravel.wsite.data.SearchCriteria#mapZoom_$eq(1 params)
    at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:222)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.filterBeanProps(BeanDeserializerFactory.java:614)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:522)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:267)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:168)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:401)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:354)
    at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:267)
    ... 9 more

The class I am trying to deserialize and serialize

@BeanInfo()
class SearchCriteria extends Serializable with McyQuantities{

  @BeanProperty val geoBox = new GeoBox()
  @BeanProperty val mapCenter: LngLat = new LngLat(0,52)
  @BeanProperty var mapZoom:Int = 4

......

**Comment by Sergey80** [comment] 2015-10-13 21:02
2.5.1 I can see same issue

**Comment by cowtowncoder** [comment] 2015-10-14 04:41
Issue on databind side does not contain enough information (in stand-alone) form to proceed, so I will reopen this issue in case problem still exists.

**Comment by cowtowncoder** [comment] 2015-10-14 04:42
If possible, would be good to verify the problem on 2.5.3 (latest 2.5), and 2.6.3 (latest stable version).
A lot has happened since the problem was reported.

**Comment by cowtowncoder** [comment] 2019-09-22 00:24
Test reproduction would be needed, and verification with newer versions. Closing: may be reopened (or probably more likely, refiled), with test + version info.

**Closed by cowtowncoder** 2019-09-22 00:24 UTC
Labels: need-test
