### ISSUE TITLE
Binding problem: missing default constructor

### ISSUE THREAD

**Issue by elthanor** [FasterXML/jackson-module-scala#317] opened 2017-02-21 16:15 UTC
Hello,
I have a problem when parsing a response like below:

```
{
  "id": "{id of the list}",
  "name": "test dev list",
  "contact": {
      "company": "",
      "address1": "",
      "address2": "",
      "city": "",
      "state": "",
      "zip": "",
      "country": "",
      "phone": ""
  },
...more stuff
}
```

so what i do is create a class with the things i am interested in at a top level in my code
`class MCList( id:String, name:String){}`

 and then try to parse a response in a function using a mapper like below:
```
def http()={
  val httpclient = {
      val requestConfig = RequestConfig
        .custom()
        .setSocketTimeout(20000)
        .setConnectTimeout(5000)
        .build()
      HttpClientBuilder
       .create()
       .setDefaultRequestConfig(requestConfig)
       .setRetryHandler(new DefaultHttpRequestRetryHandler(1, false))
       .build()
    }
    
    val request = new HttpGet("/3.0/lists/{id of list}")
    request.addHeader("Authorization", "Basic")
    val response = httpclient.execute(new HttpHost("us9.api.mailchimp.com", 443, "https"), request)
    val respBody = EntityUtils.toString(response.getEntity)
    if (response.getStatusLine.getStatusCode != 200)
      throw new RuntimeException(s"exception: $response")
    
    val mapper = new ObjectMapper()
    mapper.registerModule(DefaultScalaModule)
    mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
    var resp=mapper.readValue(respBody, Class[MCList])
    println(resp)
}
```

after the above i get

```
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class line60d78bf9c4604f828de93faebb39b39819.$read$$iwC$$iwC$$iwC$$iwC$MCList]: can not instantiate from JSON object (need to add/enable type information?)
```

spent a lot of hours on this and tried a lot of workaroundi found on the web but to no avail.
using scala module 2.8.6

Thanks for any help!

**Comment by nbauernfeind** [comment] 2018-06-29 19:12
I cannot reproduce this issue.

Where is MCList defined? If it is defined nested inside of a class or method then Jackson cannot construct one since it doesn't have a closure instance available. Can you modify my test to get it to fail? Thanks!

```scala
class MCList(id: String, name: String)

@RunWith(classOf[JUnitRunner])
class Test extends FlatSpec with Matchers {

  "it" should "just work" in {
    val m = new ObjectMapper
    m.registerModule(DefaultScalaModule)
    m.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

    val respBody = """{"id": "foo", "name": "bar", "extra": [1,2,4,5]}"""

    println(m.readValue(respBody, classOf[MCList]))
  }
}
```

**Comment by pjfanning** [comment] 2021-04-10 02:13
Closing due to lack of user response

**Closed by pjfanning** 2021-04-10 02:13 UTC
