### ISSUE TITLE
Serialize nested case object/class failed

### ISSUE THREAD

**Issue by zhan-ge** [FasterXML/jackson-module-scala#336] opened 2017-08-01 14:46 UTC
version: 2.8.9

When using `gen.writeObjectField("message", any)` which the `any` is an case object/class in some other object like below:

```
case SomeWrapper{
   case object EntityObject
   case class EntityClass(key:String)
}
```

when serializing this, will cause:

```
java.lang.InternalError: Malformed class name
  at java.lang.Class.getSimpleName(Class.java:1330)
  at com.fasterxml.jackson.databind.util.RootNameLookup.findRootName(RootNameLookup.java:43)
  at com.fasterxml.jackson.databind.cfg.MapperConfigBase.findRootName(MapperConfigBase.java:578)
  at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:280)
  at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2493)
  at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:378)
  at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1662)
..............
```

How can I fix this? Thanks a lot!

**Comment by nbauernfeind** [comment] 2018-06-29 18:45
Using 2.8.9 I can't seem to reproduce your issue. Can you modify my test to make it fail?
```scala
case object SomeWrapper {
  case object EntityObject
  case class EntityClass(key: String)
}

case class SomeWrapper2(wrap: String) {
  case object EntityObject
  case class EntityClass(key: String)

  def newEC(key: String) = EntityClass(key)
}

@RunWith(classOf[JUnitRunner])
class Test extends FlatSpec with Matchers {

  "jsm" should "work" in {
    val mapper = new ObjectMapper with ScalaObjectMapper
    mapper.registerModule(DefaultScalaModule)
    val factory = new JsonFactory()
    factory.setCodec(mapper)
    val gen = factory.createGenerator(System.out)

    gen.writeStartObject()
    gen.writeObjectField("a", SomeWrapper)
    gen.writeObjectField("b", SomeWrapper.EntityObject)
    gen.writeObjectField("c", SomeWrapper.EntityClass("foo"))
    gen.writeObjectField("d", SomeWrapper2("bar"))
    gen.writeObjectField("e", SomeWrapper2("bar").EntityObject)
    gen.writeObjectField("f", SomeWrapper2("bar").newEC("foo"))
    gen.writeEndObject()
    gen.close()
  }
}
```

**Comment by pjfanning** [comment] 2021-04-10 02:12
closing due to lack of user response

**Closed by pjfanning** 2021-04-10 02:12 UTC
