### ISSUE TITLE
Constructor selection is not deterministic

### ISSUE THREAD

**Issue by the-zorro** [FasterXML/jackson-module-scala#176] opened 2015-01-06 04:54 UTC
Not sure what causes the problem but the following "enum holder" will be serialized in "old" format (with enumClass and value):

``` scala
case class ParameterValidationData(@JsonScalaEnumeration(classOf[ParameterTypeHelper])
                                   `type`: ParameterType.ParameterType,
                                   defaultValue: String) {
  def this(`type`: ParameterType) = this(`type`, `type` match {
    case ParameterType.IntType => "0"
    case ParameterType.DoubleType => "0.0"
    case ParameterType.StringType => ""
    case ParameterType.BooleanType => "false"
  })
}
```

and will serialize correctly when `type` changed to valueType

**Comment by christophercurrie** [comment] 2015-01-06 05:41
That's quite strange. I'll have to dig into the example and see if I can figure out what causes it.

**Comment by the-zorro** [comment] 2015-01-06 09:44
It seems the annotation gets missed from those members for some reason.

**Comment by christophercurrie** [comment] 2015-01-11 20:55
I'm unable to reproduce this using Jackson 2.4.4. Can you provide a more complete example that demonstrates the problem?

**Comment by christophercurrie** [comment] 2015-02-01 20:31
I'm resolving this for now as I can't reproduce it. If you can provide a complete test case that demonstrates the issue against 2.4 or 2.5, feel free to open a new issue.

**Comment by the-zorro** [comment] 2015-02-20 04:01
Seems it was not about `type`, but about second constructor. Probably, changing the name of the field just changed the order of constructor selection. Adding @JsonScalaEnumeration to second constructor made it work better.
Sorry for bothering.

**Comment by christophercurrie** [comment] 2015-02-20 20:04
Ah, interesting. Thanks for following up; constructor selection should definitely be deterministic and predictable. I'll reopen this to ensure we address that issue.

**Comment by hjsl** [comment] 2017-06-05 09:25
I've had problems with constructor selection not being deterministic as well. My setup looks a bit different, so I thought I would add the example here to make finding the problem easier.

For me, the below test is non-deterministic. It mostly fails, but succeeds about 1 in 10 runs.

```scala
class ConstructorTest {
  @Test
  def nonDeterministicBehavior() {
    val mapper = new ObjectMapper()
    mapper.registerModule(new ScalaAnnotationIntrospectorModule() {})
    val invoiceId = mapper.readValue(""""123"""", classOf[InvoiceId])
    assertEquals(123, invoiceId.id)
  }
}

case class InvoiceId(id: Long) {
  def this(id: String) = this(id.toLong)
}
```

If I don't register `ScalaAnnotationIntrospectorModule` to the `ObjectMapper`, it seems to succeed deterministically.

Instead, if I add a third constructor to the `InvoiceId` class, it also seems to succeed every time.

```scala
case class InvoiceId(id: Long) {
  def this(id: String) = this(id.toLong)
  def this(id: Int) = this(id.toLong)
}
```

Finally, if I make it a regular class rather than a case class, it also seems to work fine.

```scala
class InvoiceId(val id: Long) {
  def this(id: String) = this(id.toLong)
}
```

**Comment by hjsl** [comment] 2017-06-05 13:05
After debugging a bit, I have a theory on what goes wrong. (Disclaimer: I'm not familiar with the Jackson or jackson-module-scala code bases.)

The method `BeanIntrospector`.`apply`.`findConstructorParam` calls `Class.getConstructors` in order to figure find the "primary constructor".

```scala
val primaryConstructor = c.getConstructors.headOption
```

The problem here is that I don't think this assumed ordering is guaranteed by Java. The JavaDoc for [`getConstructors`](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getConstructors--) does not say anything about ordering, but [`getDeclaredConstructors`](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredConstructors--) does. It explicitly says: 

>The elements in the array returned are not sorted and are not in any particular order.

And at least in the version of Java I'm using (1.8.0_121) `getConstructors` and `getDeclaredConstructors` forward to the same native implementation method `getDeclaredConstructors0`, so I think it is safe to assume this non-guarantee applies to `getConstructors` as well.

Exactly how this leads to the bug, I'm not sure. But I have seen that whether or not my test (see comment above) succeeds or fails is directly correlated to which constructor is returned first by `getConstructors`.

**Comment by davseitsev** [comment] 2017-10-26 10:48
I faced exactly the same issue, custom constructor causes JsonMappingException.
And I agree with @hjsl that it might be caused by `c.getConstructors.headOption` https://github.com/FasterXML/jackson-module-scala/blob/jackson-module-scala-2.8.8/src/main/scala/com/fasterxml/jackson/module/scala/introspect/BeanIntrospector.scala#L57

**Comment by davseitsev** [comment] 2017-10-26 12:07
The issue is definitely in https://github.com/FasterXML/jackson-module-scala/blob/jackson-module-scala-2.8.8/src/main/scala/com/fasterxml/jackson/module/scala/introspect/BeanIntrospector.scala#L57

I wrote a test where I print head constructor via `c.getConstructors.head` and then deserialize data.
Each time when I got JsonMappingException I see that `c.getConstructors.head` returned wrong constructor.

As I can see, the only way to solve it is to make developers mark desired constructor with @JsonCreator if there are more then 1 constructor in the class.

**Comment by zsxwing** [comment] 2018-11-12 13:32
Just hit this issue. The order of constructors returned by `getConstructors` is non-deterministic because JVM sorts the method list using the memory address. See the following links if you are interested in the codes that sort the methods:

- https://github.com/unofficial-openjdk/openjdk/blob/9468cb28c956e35b1aa42d76822940840a906438/src/hotspot/share/classfile/classFileParser.cpp#L6336
- https://github.com/unofficial-openjdk/openjdk/blob/9468cb28c956e35b1aa42d76822940840a906438/src/hotspot/share/classfile/classFileParser.cpp#L3053
- https://github.com/unofficial-openjdk/openjdk/blob/27e990d37f8076d1ed06888f8f6df7d60325536d/src/hotspot/share/oops/method.cpp#L1601
- https://github.com/unofficial-openjdk/openjdk/blob/b6d1d9131789829e7f45db81003269a4618e4ae6/src/hotspot/share/oops/symbol.hpp#L267

Although `getConstructors` doesn't mention anything abouth the ordering, but [getDeclaredConstructors](https://docs.oracle.com/javase/10/docs/api/java/lang/Class.html#getDeclaredConstructors()) says:
> The elements in the array returned are not sorted and are not in any particular order.

**Comment by zsxwing** [comment] 2018-11-12 13:39
Is it okey to sort the constructor list in `jackson-module-scala` so that the behavior will be deterministic? `Non-deterministic` means it may pass tests but crash in production.

**Comment by pjfanning** [comment] 2021-09-03 23:58
In jackson-module-scala 2.12.x, this seems to work - see tests like https://github.com/FasterXML/jackson-module-scala/commit/85550eaf009b80af0714417389316c5f765b550d

**Closed by pjfanning** 2021-09-03 23:58 UTC
