### ISSUE TITLE
Option[SomeTrait] not supported?

### ISSUE THREAD

**Issue by caturner81** [FasterXML/jackson-module-scala#279] opened 2016-08-25 00:25 UTC
``` scala
trait SomeTrait

case class Child(str: String) extends SomeTrait

case class Parent(child: Option[SomeTrait])

val mapper = new ObjectMapper()
mapper.registerModule(DefaultScalaModule)

val child = Child("something")
val parent = Parent(Some(child))

println(mapper.writeValueAsString(parent))
```

I expect the above to produce

``` json
{"child":{"str":"something"}}
```

Instead if produces

``` json
{"child":{}}
```

Is this expected for some reason?

**Comment by brharrington** [comment] 2016-09-04 01:13
I think this is the same as #240.

**Comment by nbauernfeind** [comment] 2016-09-05 01:02
I think you might be right @brharrington. What version of scala, jackson and jackson-module-scala are you using @caturner81?

**Comment by caturner81** [comment] 2016-09-05 17:47
Using Scala 2.11.  I had tried both 2.7.5 and 2.8.0-rc2 which were all that was available at the time.  2.8.2 seems to work as expected, so looks like it got fixed somewhere in there.

**Comment by viirya** [comment] 2016-12-26 05:40
Looks like the fixing #271 was merged after 2.8.0.rc2. Please check out

https://github.com/FasterXML/jackson-module-scala/compare/jackson-module-scala-2.8.0.rc2...master

**Comment by cowtowncoder** [comment] 2019-09-22 00:32
Assuming fix was legit -- please re-open if not, along with version information of a more recent version that can reproduce problem (like 2.9.9)

**Closed by cowtowncoder** 2019-09-22 00:32 UTC
