### ISSUE TITLE
Static JsonCreator method does not work when using DefaultScalaModule

### ISSUE THREAD

**Issue by mbknor** [FasterXML/jackson-module-scala#229] opened 2015-11-02 11:45 UTC
This bug makes it impossible to use DefaultScalaModule together with Dropwizards.

DefaultScalaModule fails while processing https://github.com/dropwizard/dropwizard/blob/master/dropwizard-util/src/main/java/io/dropwizard/util/Duration.java

Relates to https://github.com/FasterXML/jackson-module-scala/issues/221

I will supply PR with test that shows this issue

**Comment by jarreds** [comment] 2016-01-15 01:14
This is huge is still a big problem for us. Has anyone taken a look at this?

**Comment by cowtowncoder** [comment] 2016-01-15 03:23
@jarreds It may make sense to ask on `jackson-dev` list -- not many developers follow github issue updates. I don't work on Scala module myself, and I think Christopher C hasn't had time to spend on it either. So I doubt anyone has looked into this at all. But finding someone with time and itch would be easiest to do via mailing list.

**Comment by nbauernfeind** [comment] 2016-03-01 06:50
A bug fix for this (hopefully works) is going to be released in v2.6.5, and v2.7.2 (note: 2.7.0/2.7.1 are not going to be released since they won't work). Can you please upgrade and check if #236 fixes your issue?

**Comment by kelnos** [comment] 2016-03-08 11:47
Hi, I'm experiencing this problem as well, and can confirm that 2.6.5 does *not* fix this issue.

**Comment by nbauernfeind** [comment] 2016-03-08 16:35
For me to reproduce I should be able to create a dropwizard project where the configuration contains a single Duration? Or do you think there is something more involved than that?

**Comment by cowtowncoder** [comment] 2016-03-08 19:08
Ideally of course wouldn't require dep to dropwizard. But I think it has some custom deserializers of its own, for `Duration` specifically?

**Comment by kelnos** [comment] 2016-03-08 21:23
Don't even need that; there's `Duration` in the default builtin config, so just a skeleton is fine.  Let me see if I can throw something on GH...

DW doesn't use custom deserializers for `Duration`, it just has the `@JsonCreator` and `@JsonValue` annotations.

**Comment by kelnos** [comment] 2016-03-08 21:37
Ok, here's a test case: https://github.com/kelnos/dw9-jackson-scala-failure-repro -- instructions are in the README.

**Comment by kelnos** [comment] 2016-03-09 01:00
Can also confirm that disabling `ParanamerAnnotationIntrospector` as described in https://github.com/FasterXML/jackson-module-scala/issues/221#issuecomment-147693393 works around the issue and allows DW9 to start properly.

**Comment by jimm-porch** [comment] 2016-03-23 21:32
I can confirm that removing a custom deserializer for `Duration` fixes this in 2.6.3.

**Comment by nbauernfeind** [comment] 2016-04-26 02:29
Thank you, @kelnos, for providing a test case.

I've discovered that this issue has nothing at all to do with the Scala Module, _except_ that we use / register a ParanamerAnnotationIntrospector (as somewhat alluded to in #221). If you create a module that _only_ registers Paranamer it has this issue. I will still see what I can do to follow up and/or fix since it is a scala module dependency.

This is the minimal failing test I've found so far (and the serialization half is fine):
```scala
object Test extends App {
  val mapper = new ObjectMapper with ScalaObjectMapper
  mapper.registerModule(new JacksonModule {
    this += (_.appendAnnotationIntrospector(new ParanamerAnnotationIntrospector()))
  })
  val ser = mapper.writeValueAsString(Duration.minutes(1))
  val x = mapper.readValue[Duration](ser)
}
```

**Comment by pjfanning** [comment] 2021-09-04 08:49
closing this - probably fixed with https://github.com/FasterXML/jackson-databind/issues/1001 -- please reopen if it is still an issue

**Closed by pjfanning** 2021-09-04 08:49 UTC
