### ISSUE TITLE
Tests failing on fresh master build

### ISSUE THREAD

**Issue by jeff303** [FasterXML/jackson-module-scala#476] opened 2020-10-21 03:12 UTC
I did a new fork, and ran `sbt test` with all the defaults (appears to use Scala 2.13).

```
[info] *** 5 TESTS FAILED ***
[error] Failed tests:
[error]         com.fasterxml.jackson.module.scala.deser.CreatorTest
[error]         com.fasterxml.jackson.module.scala.deser.OptionDeserializerTest
[error]         com.fasterxml.jackson.module.scala.ser.CaseClassSerializerTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
```

Is this a known issue?  I tried doing a search, but didn't find anything.

**Comment by cowtowncoder** [comment] 2020-10-21 03:25
Yes, this is a long-standing issue. `master` is for future 3.0 development and most current work is on 2.x (currently `2.12`).
Work on Scala module has reduced remaining issues but there are couple of missing cases still.

**Comment by pjfanning** [comment] 2020-11-15 11:15
Closing as duplicate of https://github.com/FasterXML/jackson-module-scala/issues/431

**Closed by pjfanning** 2020-11-15 11:15 UTC
