### ISSUE TITLE
ScalaObjectMapper backward compatibility

### ISSUE THREAD

**Issue by smadarasmi** [FasterXML/jackson-module-scala#451] opened 2020-06-13 15:33 UTC
Hello, 

I have a library which has a dependency on `jackson-module-scala` version `2.9.7`. It contains this object: 

```
import com.fasterxml.jackson.databind._
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper

val Mapper = new ObjectMapper() with ScalaObjectMapper
```

I excluded this dependency from the library and my project uses `jackson-module-scala` version `2.10.3`. However, it seems like this version was intended to support backward compatibility since it still has a deprecated `ScalaObjectMapper` defined in the `experimental` module. 

But I get this exception: 
```
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper.$init$(Lcom/fasterxml/jackson/module/scala/experimental/ScalaObjectMapper;)V
```

So I'm not sure if the backward compatibility was done correctly. Do you think this should be fixed in version 2.10.x?

**Comment by pjfanning** [comment] 2020-06-13 16:23
The release is source compatible but may not be binary compatible. Could you see about getting your other dependency rebuilt with a more up to date Jackson version?

Sent from Yahoo Mail on Android 
 
  On Sat, 13 Jun 2020 at 17:33, smadarasmi<notifications@github.com> wrote:   


Hello,

I have a library which has a dependency on jackson-module-scala version 2.9.7. It contains this object:
import com.fasterxml.jackson.databind._
import com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper

val Mapper = new ObjectMapper() with ScalaObjectMapper

I excluded this dependency from the library and my project uses jackson-module-scala version 2.10.3. However, it seems like this version was intended to support backward compatibility since it still has a deprecated ScalaObjectMapper defined in the experimental module.

But I get this exception:
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper.$init$(Lcom/fasterxml/jackson/module/scala/experimental/ScalaObjectMapper;)V

So I'm not sure if the backward compatibility was done correctly. Do you think this should be fixed in version 2.10.x?

**Comment by cowtowncoder** [comment] 2020-11-21 00:26
Since the latest version of Jackson is 2.11, and we are about to release 2.12 in a week or two, I am not sure this is relevant any more.

**Closed by cowtowncoder** 2020-11-21 00:26 UTC

**Comment by eugeniyk** [comment] 2021-01-13 01:45
This issue is still relevant between 2.9.x (legacy clients) and 2.10.x/2.11.x/2.12.x

**Comment by eugeniyk** [comment] 2021-01-13 05:07
@cowtowncoder please take a look at #492 fix, thanks

**Comment by cowtowncoder** [comment] 2021-01-16 02:50
@eugeniyk I do not actually maintain this module; @pjfanning would be the authority here.
