### ISSUE TITLE
java Iterable serialization bug

### ISSUE THREAD

**Issue by fkowal** [FasterXML/jackson-module-scala#235] opened 2016-02-18 06:25 UTC
Hi i found a strange bug resulting in ArrayOutOfBoundsException

It's triggered when serializing z java Iterable<>
A simple test repo demonstrating the bug is here
```
git clone https://github.com/fkowal/jackson-bug-report
cd jackson-bug-report
./gradlew test -i
```

Test.scala
```scala
package pl.test

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import org.junit.Test

class JacksonTest {

  @Test
  def unexpectedArrayIndexOutOfBoundsException(): Unit = {
    // given
    val sut = new MyIterable()
    val objectMapper = new ObjectMapper()
    objectMapper.registerModule(DefaultScalaModule) // removing scalaModule fixes the test

    // when
    val str = objectMapper.writeValueAsString(sut)

    assert(str != null, "result is null")
    assert(str == """["a","b"]""", s"${str} != [a,b]")
  }
}
```
MyIterable.java
```java
package pl.test;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.stream.Collector;

public class MyIterable implements Iterable<String> {
    private final List<String> strings = new ArrayList();

    public MyIterable() {
        strings.add("a");
        strings.add("b");
    }

    public MyIterable(Collection<String> strs) { // removing this constructor or the status collector() method fixes the test
        this.strings.addAll(strs);
    }

    public static Collector<String, MyIterable, MyIterable> collector() {
        return Collector.of(MyIterable::new, MyIterable::addError, MyIterable::combine);
    }

    @Override
    public Iterator<String> iterator() {
        return strings.iterator();
    }

    public MyIterable addError(String str) {
        strings.add(str);
        return this;
    }

    public MyIterable combine(MyIterable iter) {
        this.strings.addAll(iter.strings);
        return this;
    }
}
```

stacktrace looks like this
```
java.lang.ArrayIndexOutOfBoundsException: 13057

	at com.fasterxml.jackson.module.paranamer.shaded.BytecodeReadingParanamer$ClassReader.accept(BytecodeReadingParanamer.java:563)
	at com.fasterxml.jackson.module.paranamer.shaded.BytecodeReadingParanamer$ClassReader.access$200(BytecodeReadingParanamer.java:338)
	at com.fasterxml.jackson.module.paranamer.shaded.BytecodeReadingParanamer.lookupParameterNames(BytecodeReadingParanamer.java:103)
	at com.fasterxml.jackson.module.paranamer.shaded.CachingParanamer.lookupParameterNames(CachingParanamer.java:79)
	at com.fasterxml.jackson.module.paranamer.ParanamerAnnotationIntrospector._findParaName(ParanamerAnnotationIntrospector.java:71)
	at com.fasterxml.jackson.module.paranamer.ParanamerAnnotationIntrospector.findImplicitPropertyName(ParanamerAnnotationIntrospector.java:56)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findImplicitPropertyName(AnnotationIntrospectorPair.java:467)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findImplicitPropertyName(AnnotationIntrospectorPair.java:466)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreatorParam(POJOPropertiesCollector.java:436)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addCreators(POJOPropertiesCollector.java:415)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:285)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueMethod(POJOPropertiesCollector.java:169)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueMethod(BasicBeanDescription.java:222)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:355)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:210)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:153)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1203)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1157)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:481)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:679)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:107)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3559)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2927)
	at pl.test.JacksonTest.unexpectedArrayIndexOutOfBoundsException(JacksonTest.scala:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by probert100** [comment] 2016-03-02 17:51
Looks like I have the same issue. Did you find a solution?

**Comment by nbauernfeind** [comment] 2016-03-02 18:27
i can confirm that this test was broken in 2.6.4 but is fixed in both 2.6.5 and 2.7.2. Can you upgrade to one of these versions and try again?

**Comment by probert100** [comment] 2016-03-02 18:50
Looks like switching to 2.7.2 fixed the issue for me. Thanks for your help!

**Comment by nbauernfeind** [comment] 2016-03-02 18:55
No problem!

**Closed by nbauernfeind** 2016-03-02 18:55 UTC
