### ISSUE TITLE
Annotation is not working properly under version 2.5.1

### ISSUE THREAD

**Issue by zhijun** [FasterXML/jackson-module-scala#186] opened 2015-02-26 12:59 UTC
I use both jackson-dataformat-xml andjackson-module-scala. After upgrading from 2.4.5 to 2.5.1, @JacksonXmlProperty(isAttribute = true) was no longer working. 
# Here's code:

```
  case class Tst(@JacksonXmlProperty(isAttribute = true)b:String){
    @JacksonXmlProperty(isAttribute = true)
    val a:String="a value"
  }
  val xmlmapper = new XmlMapper with ScalaObjectMapper
  xmlmapper.registerModule(DefaultScalaModule)
  val xml=xmlmapper.writeValueAsString(Tst("b value"))
#   println(xml)
```

2.4.5 output:

```
    <Tst b="b value" a="a value"/>
```

2.5.1 output:

```
    <Tst a="a value"><b>b value</b></Tst>
```

Annotation(s) are ignored with case class constructor parameters.

**Comment by zhijun** [comment] 2015-02-26 13:01
![tst](https://cloud.githubusercontent.com/assets/875303/6392338/a478b93a-bdfa-11e4-8ecb-e5ac910f2fbe.png)

**Comment by christophercurrie** [comment] 2015-02-26 18:16
Thanks for the report, I'll look into this. As a workaround, you can try using the scala meta annotations to attach the annotations differently:

```scala
import scala.annotations.meta._

case clas Tst(@(JacksonXmlProperty @field @getter)(isAttribute=true) b: String) {
@(JacksonXmlProperty @field @getter)(isAttribute=true) a: String
} 
```

Let me know if this works for you.

**Comment by zhijun** [comment] 2015-02-27 00:47
After testing I confirm your workaround really worked! 
However as there are so many annotations in my tons of case classes, I prefer to hold upgrading to 2.5.x until this issue is fixed. Thank you for being responsive and looking forward to further update!

**Comment by zhijun** [comment] 2015-07-01 08:09
May I ask if there is any plan for this issue?

**Comment by christophercurrie** [comment] 2015-07-01 20:01
I suspect this issue has the same root cause as #205; at this time I haven't been able to track down and resolve that issue. It remains at the top of my list of things to fix, but it requires additional time I haven't had to devote to it.

**Comment by pjfanning** [comment] 2022-08-08 16:00
Closing this based on https://github.com/FasterXML/jackson-module-scala/issues/176 being closed - please reopen if users have this issue with recent releases.

**Closed by pjfanning** 2022-08-08 16:00 UTC
