### ISSUE TITLE
Case class with Seq parameter default = Nil and  not supported, deserialized to null

### ISSUE THREAD

**Issue by kfiron** [FasterXML/jackson-module-scala#87] opened 2013-06-24 12:45 UTC
# Given case class:

case class Cat(name : String, kittens: Seq[Cat] = Nil)
# Read in test:

mapper.readValue("{\"name\":\"kozmo\"}", classOf[Cat])
# Expected:

expected cat with Nil kittens, however it is null. it seems like SeqModule does not check for the default value if the parameter does not provieded

**Comment by yairogen** [comment] 2015-02-17 08:15
I also have the same issue. When will this fix be released?

**Comment by christophercurrie** [comment] 2015-02-17 17:05
There is no fix currently ready for this issue. #170 made a very strong start at it, but had some issues that needed resolving before it could be merged. I don't have a timeline for when this issue might be resolved, as it requires either (a) abandoning Scala 2.10, which does not have thread-safe reflection, or (b) re-implementing the Scala reflection support for detecting and invoking default parameter value functions. Neither of these is a quick fix.

**Comment by yairogen** [comment] 2015-02-17 17:10
I would branch and support in 2.11 although still open in 2.10. 

It will at least enable some users to benefit from this fix. 

Better than nothing, but that's just my 2 cents.

**Comment by cowtowncoder** [comment] 2015-02-17 18:38
Branching is tempting from user perspective, but amount of work needed makes it less than ideal for people who actually support the project. This is especially because we have maintenance branches for old versions; and since Scala's backwards compatibility has been quite challenging this would just add one more dimension to the puzzle.

So branching may not be worth the cost here, unfortunately.
Although maybe  there's a way to do multi-module project for "legacy" version of 2.10, to avoid multi-dimensional git branches.

**Comment by yairogen** [comment] 2015-02-18 10:58
I see you point. Is the multi-module option something you can do? I assume that as the time passes more and more 2.11 users will be out there and can benefit from this.

**Comment by christophercurrie** [comment] 2015-02-18 16:38
This *might* be possible, it's not an option I had considered. I'll look into it to see how difficult it might be. At earliest it will be for Jackson 2.6, as it would probably require some changes to the dependency structure.

**Comment by yairogen** [comment] 2015-02-19 06:50
Better 2.6 than later. I appreciate your efforts. Thanks. Looking forward for an update.

**Comment by vkuptcov** [comment] 2016-03-03 15:29
Recently I found a nice library, which could help https://github.com/mesosphere/jackson-case-class-module/

**Comment by normana400** [comment] 2016-03-22 17:16
is there an update on this? seems like this issue has gone dormant for about a year, but its a pretty basic blocking feature for anyone wanting to use jackson with scala.

**Comment by mancvso** [comment] 2016-03-31 20:54
In 2.7.1 Scala module still does not support default values.

**Comment by cowtowncoder** [comment] 2016-03-31 23:32
I'm pretty sure there would be an update if support for default values was added, either by Scala runtimes implementing this in more easily supportable form, or by workaround on jackson scala module.

**Comment by mancvso** [comment] 2016-04-22 18:48
How can it be in a more easily supportable form?
We can hack up a SIP (Scala Improvement Process) document if it's needed.

**Comment by cowtowncoder** [comment] 2016-04-22 22:17
@mancvso I probably should not have pointed to Scala runtime as I do not know enough to be sure (it was based on recollection of earlier discussions with @christophercurrie but I may have mixed up things). @nbauernfeind would probably know if something was needed.

In general support for default values from Jackson is not easy to support: per-type defaults are not too difficult (although even then only apply to things passed internally via Creators), but things that vary at per-constructor-parameter level have no support from databind.

**Comment by scosenza** [comment] 2016-04-23 02:52
For those following this issue, you may be interested in Twitter's
finatra-jackson <https://github.com/twitter/finatra/tree/develop/jackson>
module which augments jackson-module-scala in several keys ways. Notably,
finatra-jackson is usable outside the Finatra framework, and supports
default values, required fields, and validations which accumulate errors.
For more details, please visit our documentation at:
http://twitter.github.io/finatra/user-guide/json/

-Steve Cosenza

**Comment by nbauernfeind** [comment] 2016-04-25 11:17
@scosenza Thanks! I did not know finatra-jackson existed. I will take a look and see what I can pull into our implementation.

**Comment by nbauernfeind** [comment] 2016-04-25 22:07
@scosenza FWIW, it looks like finatra-jackson only supports default values on case classes.

**Comment by dotta** [comment] 2016-05-02 15:51
Since this wasn't obvious to me, I'm sharing a workaround for this issue (hoping it will be useful to others).

I had the following class:

```
case class User(userId: String, name: String, friends: Seq[String] = Seq.empty) {
```

Which wasn't "correctly" handled by jackson because of the default argument (i.e., a `null` value was  assigned to `User#friends`).

But, after refactoring it to:

```
case class User @JsonIgnore() (userId: String, name: String, friends: Seq[String]) {
  def this(userId: String, name: String) = this(userId, name, Seq.empty)
}
```

It all worked.

And here is a test that now succeeds:

```
class UserTest {
  @Test
  def test() {
    val mapper = new ObjectMapper() with ScalaObjectMapper
    mapper.registerModule(DefaultScalaModule)
    val actual = mapper.readValue[User]("""{"userId":"asd","name":"asd"}""")
    Assert.assertEquals(new User("asd", "asd"), actual)
  }
}
```

**Comment by michaelhixson** [comment] 2016-06-04 07:27
Would this change to `jackson-databind` in 2.8.0-SNAPSHOT help?

https://github.com/FasterXML/jackson-databind/pull/1224

In `jackson-module-kotlin` at least, it was enough to support Kotlin's language-level default method arguments.  We were hoping that it could be used in Scala too, but AFAIK no one proved that out.

High level steps:

1. Create a `StdValueInstantiator` that overrides the new `createFromObjectWith(DeserializationContext, SettableBeanProperty[], PropertyValueBuffer)` method.

2. In that method, loop over the bean properties and use `buffer.hasParameter(prop)` to discover which ones actually appeared in the JSON source, and grab each present value using `buffer.getParameter(prop)`.

3. Also in that method, obtain a reference to the creator method (via `_withArgsCreator`) and use reflection to figure out which parameters are optional (i.e. have default values).  Then invoke that creator method while leaving out all the missing-and-optional values.

**Comment by christophercurrie** [comment] 2016-06-07 01:14
The challenge has never been, to my knowledge, lack of support from Jackson core. The obstacle is that the state of Scala reflection historically did not make identifying defaulted parameters and evaluating the default values a straightforward process.

Prior to Scala 2.10, there was no Scala reflection library, so determining which methods had default parameters and where to find their defaults relied on either error-prone heuristics on top of Java reflection, or parsing of the ScalaSig annotation, for which tooling was poor.

It was hoped that Scala 2.10 would help remedy this issue, but that version of `scala-reflect` [is not thread safe and cannot be made to be](https://issues.scala-lang.org/browse/SI-6240); i.e. techniques like a thread-safe wrapper object can't help us here.

If support for Scala 2.10 were dropped, it is conceivable that this issue could be resolved. It's also possible that this feature could be implemented as a Scala 2.11 only feature, though there's little infrastructure within the project currently for features to target only one Scala version; the best bet would be for a separate add-on module to provide the needed support, and expose only a Scala 2.11 build.

**Comment by stuz5000** [comment] 2016-06-07 16:14
Is lack of thread safety a real issue? Independently, for serialization
efficiency, it seems that the right think to do is to do reflection up
front (and can be in a single thread), and separate it from the execution
of the serialization.

On Mon, Jun 6, 2016 at 6:14 PM, Christopher Currie <notifications@github.com

**Comment by nbauernfeind** [comment] 2016-06-07 16:44
How would you enforce the coordination of single-threaded reflection with
users of jackson (and any other third party libraries that use it)?

**Comment by christophercurrie** [comment] 2016-06-07 17:08
@stuz5000 Unfortunately there's just no way to make that work due to inherent issues with 2.10 reflection. From the comments on the JIRA issue:

> just adding a TypeTag context bound to a method is enough to make it non-threadsafe

This is just one of multiple challenges. It took a large amount of effort to fix in 2.11, and several attempts were made to back-port the fix to 2.10 without success. Believe me, if there were a workaround, someone would have found it and we'd be applying it here.

**Comment by cowtowncoder** [comment] 2016-06-07 18:03
@stuz5000 As far as I recall it's not question of trying to optimize away multi-threaded access, but rather that pieces of Scala runtime do not have thread-safe handling of crucial state, leading to state corruption in unpredictable ways (that is, order of calls from different callers leads to different error modes). And unfortunately such lack of synchronization is very difficult of not downright impossible to work around from the outside.

I think it would make sense to start discussion on mailing list on when to drop Scala 2.10 support for new minor versions.

**Comment by mkalish** [comment] 2016-12-14 22:43
With scala 2.12 released, has there been any change around dropping support for 2.10 and adding this feature?

**Comment by cowtowncoder** [comment] 2016-12-14 23:07
Scala 2.10 still supported by Jackson 2.8. I don't remember if dropping scala 2.10 for jackson 2.9 has been decided; there is some concern about wide use (still) of 2.10.

**Comment by nicojs** [comment] 2017-01-17 12:37
@cowtowncoder could you provide an update on this? What are the time lines on dropping scala 2.10 support and releasing jackson 2.9?

**Comment by cowtowncoder** [comment] 2017-01-17 20:41
@nicojs for update, please bring this up on dev mailing list. No new discussions regarding scala compatibility. Also, not much activity wrt module, no new development.

On Jackson 2.9: was hoping to get rc1 out by january. Not happening, so release no sooner than March 2017. Perhaps rc1 late february if things go well.

**Comment by nicojs** [comment] 2017-01-18 11:14
Do you mean this list? https://groups.google.com/forum/#!forum/jackson-dev

**Comment by cowtowncoder** [comment] 2017-01-18 18:29
@nicojs Yes, this is related more to development of Jackson (otherwise `jackson-user`), so I think that is correct.

**Comment by talbenshabtay** [comment] 2017-04-26 05:46
still failing with version 2.8.7
tried @dotta solution but it seems jackson response is non-deterministic i get a roughly 33%
chance that default values will be set.

i hacked a solution using json4s .
`
implicit val formats = DefaultFormats
...
def read[T](str:String) = parse(str).extract[T]
`

build.sbt adding the following
"org.json4s" %% "json4s-native" % "3.5.1",
    "org.json4s" %% "json4s-jackson" % "3.5.1"

**Comment by kylejmcintyre** [comment] 2017-06-19 15:43
Big warning on the def this() workaround: You must add the @JsonCreator annotation to that constructor, otherwise you may see non-deterministic deserialization behavior across process runs on certain JVM/system configurations (I've confirmed it on Hotspot JVM/Java 8/Mac OSX but believe it's also happening on Linux). See https://github.com/FasterXML/jackson-module-scala/issues/159 for more information.

**Comment by alain-marcel** [comment] 2019-06-16 12:49
May scala 2.13 help to solve the issue, or dotty 0.16.0-RC3  ?

**Comment by plokhotnyuk** [comment] 2019-06-16 12:55
@alain-marcel As W/A use [jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala) - it deserializes properly default values for all supported types including Scala collections. Also it is much safe and [efficient in runtime](https://plokhotnyuk.github.io/jsoniter-scala/).

**Comment by jroper** [comment] 2019-12-05 01:02
Presumably, this should be trivial to implement, just override `AnnotationIntrospector.findPropertyDefaultValue`. If the class the property is on is a Scala case class, and there is no default value declared for the property using a `JsonProperty` annotation, and there is a synthetic method that provides the default value (this can be determined just by understanding how Scala generates the bytecode for default values), then invoke that method to get the default value.

**Comment by jroper** [comment] 2019-12-05 01:39
So, `AnnottaionIntrospector.findPropertyDefaultValue` wouldn't work, because it just returns `String`, and is only for documentation purposes - Jackson databind doesn't use it at all. So, once https://github.com/FasterXML/jackson-modules-base/issues/23 is implemented, this feature can be implemented.

**Comment by cowtowncoder** [comment] 2019-12-05 03:02
Kotlin module (https://github.com/FasterXML/jackson-module-kotlin) actually supports this, if anyone wants to have a look; I think it is via

    src/main/kotlin/com/fasterxml/jackson/module/kotlin/KotlinValueInstantiator.kt

and uses `ValueInstantiator` extension point (possible coupled with `getNullValue(...)` of `JsonDeserializer` to deal with things like "absent" `Option` instead of `null`)

**Comment by jroper** [comment] 2019-12-05 03:47
lol, I just found the `ValueInstantiator` myself and implemented it in #439.

**Comment by jroper** [comment] 2019-12-05 03:50
I like my impl better, it overrides `getFromObjectArguments` to add a `NullPropertyProvider` to any `CreatorProperty` that is backed by a constructor parameter that has a default value.

**Comment by cowtowncoder** [comment] 2019-12-05 23:48
Sounds like reasonable approach, and great improvement for Scala module in 2.11.

Just one request: if a link to this issue can be added on release notes page:

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.11

that'd be great (and whichever file(s) repo has -- I think there is separate changes/release file)

**Comment by jroper** [comment] 2019-12-10 02:16
This can be closed now that #439 is merged.

**Comment by jroper** [comment] 2019-12-10 02:19
@cowtowncoder I don't have access to edit the wiki, I'm in the FasterXML org but probably not in the right team.

**Comment by cowtowncoder** [comment] 2019-12-10 23:05
@jroper Ah. I added you to Scala team, but it won't give access to main `Jackson` repo. I think I'll need to create a different team for that.

But I think `release-notes/VERSION.md` should be fine, I can merge entries from there on short term.

**Comment by pjfanning** [comment] 2019-12-14 18:37
will be in 2.11.0 release

**Closed** 2019-12-14 18:37 UTC
Labels: Default Parameters

**Comment by wix-andriusb** [comment] 2020-01-14 20:16
When will the 2.11.0 release happen?

**Comment by pjfanning** [comment] 2020-01-14 20:39
when jackson-databind 2.11.0 is released -- can be tracked at https://github.com/FasterXML/jackson-databind/blob/master/release-notes/VERSION-2.x

**Comment by cowtowncoder** [comment] 2020-01-14 23:53
@wix-andriusb in typical OSS fashion it will be released "when it's ready", planning is not based on specific date goals. Having said that the first release candidate for 2.11 could be by early February, that is, in couple of weeks. And actual release before end of February 2020.

**Comment by mley** [comment] 2020-07-07 12:17
I came across this issue while updating our stack to Spring Boot 2.3 (which comes with jackson 2.11 by default). We are making heavy use of Scala cases classes. Using the default-value for deserialising breaks a lot of stuff at our end.

In this example it's very confusing, since the JSON value is explicitly set to null:
```
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import org.scalatest.{FlatSpec, Matchers}

case class Test(value: String = "the value")

class JacksonSpec extends FlatSpec with Matchers {
  val objectMapper = new ObjectMapper().registerModule(DefaultScalaModule)

  "Test.value" should "be deserialized correctly" in {
    objectMapper.readValue("""{"value":null}""", classOf[Test]).value shouldBe null
  }
}
```
This spec is ok with jackson 2.10.4, but fails with 2.11. Is there a way to disable this feature?

**Comment by pjfanning** [comment] 2020-07-07 15:25
wouldn't it be better to use `case class Test(value: Option[String])` if you need to support null?

**Comment by mley** [comment] 2020-07-08 05:26
@pjfanning You are right, the given test is not very idiomatic. Here is a better example, which should prove my point:

```
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.module.scala.DefaultScalaModule
import org.scalatest.{FlatSpec, Matchers}

case class Test(value: Option[String] = Some("the default"))

class JacksonSpec extends FlatSpec with Matchers {
  val objectMapper = new ObjectMapper().registerModule(DefaultScalaModule)

  "Test.value" should "be deserialized correctly" in {
    objectMapper.readValue("""{"value":null}""", classOf[Test]).value.isEmpty shouldBe true
    objectMapper.readValue("""{}""", classOf[Test]).value shouldBe Some("the default")
    objectMapper.readValue("""{"value":"the value"}""", classOf[Test]).value shouldBe Some("the value")
  }
}
```
With Jackson 2.10.4 deserialising `{}` fails (as the feature is not yet implemented).
With Jackson 2.11 deserialising `{"value":null}` fails.
